### ISSUE TITLE
Production bundling (.dmg file)

### ISSUE THREAD

**Issue by drepram** [lexmartinez/ocr-electron-vue#1]
Can you help us by building the application and then uploading the .dmg file to the release tab of this repository?

That would be a whole lot easier to run the app day-to-day instead of running it from the Terminal.

Thanks.

**Comment by lexmartinez** [comment]
Sure dude, I going to open a new milestone with that goal, since this was an academic exercise, I never prepared any kind of bundling for that, as I see I would need an extra effort in order to re-structure the project, anyway I'll do

**Comment by lexmartinez** [comment]
@caxvis done, the version 1.0.0 aka `Piper` was released today, with the new packing setup, you can download the dmg file on [releases](https://github.com/lexmartinez/ocr-electron-vue/releases/tag/1.0.0) tab.

> Please check the production notes on `README.md` file
